### ISSUE TITLE
[proposal] add the option to scope providers to paths

### ISSUE THREAD

**Issue by dkbast** [csells/go_router#185] opened 2021-11-23 11:10 UTC
I often want to provide something to a route and all its sub-routes - for example a QuizDefinition to all the quiz screens which will be added to the stack. So far I have often just added the Provider above the MaterialApp but was never really happy with that, since then I had to remember to reset the Provider etc pp.

I recognise that provider might not be the best name, but I hope it is clear what I want to achieve:

Proposal:
```
 GoRoute(
      providerBuilder: (context, navigator) => 
            Provider(create: (_)=> ProvidedObject(),
            child: navigator
      ),
      path: '/quiz',
      pageBuilder: (context, state) => MaterialPage<void>(
        key: state.pageKey,
        child: MyChild,
      ),
      routes: [...mySubRoutes], // should also apply to pages pushed on the stack imperatively
    );
```

And in go_router_delegate.dart we would have to wrap the section below with a MultiProvider or iterate over the providers which probably could be retrieved while performing the pages lookup. 

Open question: how to cache the providers so they are not rebuilt on adding a page to the stack?

```
    // wrap the returned Navigator to enable GoRouter.of(context).go()
    return builderWithNav(
      context,
      Navigator(
        restorationScopeId: restorationScopeId,
        key: _key, // needed to enable Android system Back button
        pages: pages,
        observers: observers,
        onPopPage: (route, dynamic result) {
          if (!route.didPop(result)) return false;

          log2('GoRouterDelegate.onPopPage: matches.last= ${_matches.last}');
          _matches.remove(_matches.last);
          if (_matches.isEmpty) {
            throw Exception(
              'have popped the last page off of the stack; '
              'there are no pages left to show',
            );
          }

          // this hack allows the browser's address bar to be updated after a
          // push and pressing the Back button, but it shouldn't be necessary...
          _safeNotifyListeners();

          return true;
        },
      ),
    );
```

**Comment by csells** [comment] 2021-11-23 20:25
You can [use `navigatorBuilder` to achieve what you're looking for](https://gorouter.dev/navigator-builder).

**Comment by dkbast** [comment] 2021-11-25 11:20
My main concern is that I would like to attach the information about which providers/builders should be added to the GoRoute and not have a separate object holding this information, so I might have to extend GoRoute and find a way to access it again. I was thinking, that the GoRouteMatch'es passed to _builder already has access to all GoRoute objects and that I could build something like getPages() which gets the builders for each GoRoute - I'll try that over the weekend and report back

**Comment by esDotDev** [comment] 2021-11-25 15:51
More or less a dupe of this I think https://github.com/csells/go_router/issues/133

**Comment by csells** [comment] 2021-12-03 19:10
dupe of #133

**Closed by csells** 2021-12-03 19:10 UTC
Labels: waiting on customer input
