### ISSUE TITLE
Fix nested navigation between multiple screen

### ISSUE THREAD

**Issue by mohsen-mortazavi** [csells/go_router#371] opened 2022-02-15 11:16 UTC
Hi dear GoRouter team, 
I am currently using your library in my project, but we have a problem with bottom navigation bar. 
if you are using bottom navigation bar, when you want to navigate from a screen to another one via go_router, the bottom navigation bar would generate a completely sheet which will cover the bottom navigation bar. 
It would be really kind of you if you can fix it asap. 
Thanks and regards

**Comment by romatallinn** [comment] 2022-02-18 08:32
Do you mean that the page covers the bottom navigation bar when you are switching between the tabs? Or when you navigate deeper on one of the tabs?

Either way, the package doesn't really define this behavior. It more depends on how you structure your widgets and bottom navigation bar in your project.

If you post some screenshots to clarify the problem, somebody could help you.

**Comment by csells** [comment] 2022-02-19 20:00
Closing this as a dupe of https://github.com/csells/go_router/issues/82

**Closed by csells** 2022-02-19 20:00 UTC
